language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

addons:
  apt:
    packages:
      - libevent-dev # Used by 'event' and 'libevent' PHP extensions

install:
  - ./travis-init.sh
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
