language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

# lock distro so new future defaults will not break the build
dist: precise

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm

sudo: false

addons:
  apt:
    packages:
      - libevent-dev # Used by 'event' and 'libevent' PHP extensions

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - ./travis-init.sh
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
